# Generated by Django 3.1.1 on 2021-03-24 07:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("plio", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="plio",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="plio",
            name="video",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="plio.video"
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="plio",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="plio.plio"
            ),
        ),
    ]
