# Generated by Django 3.1.1 on 2021-03-26 07:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("plio", "0002_auto_20210325_1442"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="plio",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="plio.plio"
            ),
        ),
        migrations.AlterField(
            model_name="plio",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="plio",
            name="video",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="plio.video"
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="plio.item"
            ),
        ),
    ]
