# Generated by Django 3.1.1 on 2021-03-30 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plio", "0004_auto_20210330_1211"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="options",
            field=models.JSONField(null=True),
        ),
    ]
