# Generated by Django 3.1.1 on 2021-03-30 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plio", "0005_auto_20210330_1214"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plio",
            name="uuid",
            field=models.SlugField(unique=True),
        ),
    ]
