# Generated by Django 3.1.1 on 2021-04-02 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("plio", "0008_plio_config"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="item",
            name="text",
        ),
        migrations.AddField(
            model_name="question",
            name="text",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="plio",
            name="name",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="plio",
            name="video",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="plio.video",
            ),
        ),
    ]
