# Generated by Django 3.1.1 on 2021-04-05 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plio", "0009_auto_20210402_1420"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="duration",
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="item",
            name="time",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="plio",
            name="status",
            field=models.CharField(
                choices=[("draft", "Draft"), ("published", "Published")],
                default="draft",
                max_length=255,
            ),
        ),
    ]
