# Generated by Django 3.1.1 on 2021-04-06 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plio", "0010_auto_20210405_0934"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="correct_answer",
            field=models.TextField(null=True),
        ),
    ]
