# Generated by Django 3.1.1 on 2021-04-07 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plio", "0015_auto_20210407_2139"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="type",
            field=models.CharField(
                choices=[("mcq", "Multiple Choice Question")],
                default="mcq",
                max_length=255,
            ),
        ),
    ]
