# Generated by Django 3.1.1 on 2021-04-08 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("plio", "0016_auto_20210407_2147"),
        ("plio", "0015_auto_20210408_0638"),
    ]

    operations = []
