# Generated by Django 3.1.1 on 2021-06-04 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plio", "0018_auto_20210414_1200"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="max_char_limit",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="question",
            name="type",
            field=models.CharField(
                choices=[
                    ("mcq", "Multiple Choice Question"),
                    ("subjective", "Subjective Question"),
                ],
                default="mcq",
                max_length=255,
            ),
        ),
    ]
