# Generated by Django 3.1.1 on 2021-06-04 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plio", "0019_auto_20210604_1021"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="has_char_limit",
            field=models.BooleanField(default=False),
        ),
    ]
