# Generated by Django 3.1.1 on 2021-06-14 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plio', '0021_auto_20210613_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='alt_text',
            field=models.CharField(default='Image', max_length=255),
        ),
    ]
