# Generated by Django 3.1.1 on 2021-08-30 04:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("plio", "0022_image_alt_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="plio",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="plio.plio"
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="plio.item"
            ),
        ),
    ]
