# Generated by Django 3.1.1 on 2021-07-16 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plio", "0022_image_alt_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="plio",
            name="temp_field",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
