# Generated by Django 3.1.1 on 2021-09-02 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plio", "0026_auto_20210830_0620"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="type",
            field=models.CharField(
                choices=[
                    ("mcq", "Multiple Choice Question"),
                    ("subjective", "Subjective Question"),
                    ("checkbox", "Checkbox Question"),
                ],
                default="mcq",
                max_length=255,
            ),
        ),
    ]
