# Generated by Django 3.1.1 on 2021-09-02 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plio", "0027_auto_20210902_1049"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="correct_answer",
            field=models.JSONField(null=True),
        ),
    ]
