# Generated by Django 3.1.1 on 2022-01-24 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("plio", "0028_auto_20210902_1120"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="plio",
            options={"ordering": ["-updated_at"]},
        ),
    ]
