# Generated by Django 3.1.1 on 2022-01-10 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("plio", "0028_auto_20210902_1120"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="item",
            options={"ordering": ["time"]},
        ),
        migrations.AlterModelOptions(
            name="question",
            options={"ordering": ["item__time"]},
        ),
    ]
