# Generated by Django 3.1.1 on 2022-01-25 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("plio", "0029_auto_20220124_2224"),
        ("plio", "0029_auto_20220110_1044"),
    ]

    operations = []
