# Generated by Django 3.1.1 on 2022-02-15 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plio", "0030_merge_20220125_0510"),
    ]

    operations = [
        migrations.AddField(
            model_name="plio",
            name="type",
            field=models.CharField(
                choices=[("video", "Video"), ("quiz", "Quiz")],
                default="video",
                max_length=255,
            ),
        ),
    ]
