# Generated by Django 3.1.1 on 2024-07-23 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plio', '0031_question_survey'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='option_images',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
