# Generated by Django 3.1.1 on 2021-04-01 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_auto_20210331_0633"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="deleted_at",
        ),
        migrations.AddField(
            model_name="user",
            name="deleted",
            field=models.DateTimeField(editable=False, null=True),
        ),
    ]
