# Generated by Django 3.1.1 on 2021-04-01 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_auto_20210401_1332"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="config",
            field=models.JSONField(null=True),
        ),
    ]
