# Generated by Django 3.1.1 on 2021-04-02 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_user_config"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[],
        ),
    ]
