# Generated by Django 3.1.1 on 2021-04-06 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_onetimepassword"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(max_length=128, null=True),
        ),
    ]
