# Generated by Django 3.1.1 on 2021-04-06 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_auto_20210406_1045"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="phone",
            new_name="mobile",
        ),
    ]
