# Generated by Django 3.1.1 on 2021-04-13 05:58

from django.db import migrations
from plio.settings import DEFAULT_ROLES


class Migration(migrations.Migration):
    def insert_roles(apps, schema_editor):
        # We can't import the Role model directly as it may be a newer
        # version than this migration expects. We use the historical version.
        Role = apps.get_model("users", "Role")

        for default_role in DEFAULT_ROLES:
            role = Role()
            role.name = default_role["name"]
            role.save()

    dependencies = [
        ("users", "0011_auto_20210408_1448"),
    ]

    operations = [
        migrations.RunPython(insert_roles),
    ]
