# Generated by Django 3.1.1 on 2021-04-14 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0011_auto_20210412_1819"),
        ("users", "0012_auto_20210413_0558"),
    ]

    operations = []
