# Generated by Django 3.1.1 on 2021-06-23 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0014_user_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="status",
            field=models.CharField(
                choices=[("waitlist", "Added to Waitlist"), ("approved", "Approved")],
                default="approved",
                max_length=255,
            ),
        ),
    ]
