# Generated by Django 3.1.1 on 2021-06-23 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0015_auto_20210623_0700"),
        ("users", "0015_auto_20210623_0822"),
    ]

    operations = []
