# Generated by Django 3.1.1 on 2021-06-23 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0016_merge_20210623_1241"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="auth_type",
            field=models.CharField(
                choices=[("avanti", "Avanti Fellows Authentication")],
                max_length=255,
                null=True,
            ),
        ),
    ]
