# Generated by Django 3.1.1 on 2021-06-28 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_auto_20210623_1546'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='auth_type',
        ),
    ]
