# Generated by Django 3.1.1 on 2022-03-28 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BigqueryJobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('schema', models.CharField(default='public', max_length=255)),
                ('table_to_sync', models.CharField(max_length=255)),
                ('table_last_updated_at', models.DateTimeField(null=True)),
                ('table_last_synced_at', models.DateTimeField(null=True)),
                ('last_synced_row_id', models.PositiveIntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'bigquery_jobs',
            },
        ),
    ]
