# Generated by Django 3.1.1 on 2021-04-01 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="organization",
            name="deleted_at",
        ),
        migrations.AddField(
            model_name="organization",
            name="deleted",
            field=models.DateTimeField(editable=False, null=True),
        ),
    ]
