# Generated by Django 3.1.1 on 2022-01-12 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_organization_api_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='config',
            field=models.JSONField(null=True),
        ),
    ]
