# Generated by Django 3.1.1 on 2021-03-26 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tags", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="modelhastag",
            name="tag",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="tags.tag"
            ),
        ),
    ]
