# Generated by Django 3.1.1 on 2021-03-24 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("plio", "0001_initial"),
        ("entries", "0001_initial"),
        ("experiments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sessionanswer",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="plio.question"
            ),
        ),
        migrations.AddField(
            model_name="sessionanswer",
            name="session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="entries.session"
            ),
        ),
        migrations.AddField(
            model_name="session",
            name="experiment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="experiments.experiment"
            ),
        ),
        migrations.AddField(
            model_name="session",
            name="plio",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="plio.plio"
            ),
        ),
    ]
