# Generated by Django 3.1.1 on 2021-03-26 07:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("experiments", "0004_auto_20210326_0723"),
        ("plio", "0003_auto_20210326_0723"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("entries", "0003_auto_20210325_1442"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="entries.session"
            ),
        ),
        migrations.AlterField(
            model_name="session",
            name="experiment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="experiments.experiment",
            ),
        ),
        migrations.AlterField(
            model_name="session",
            name="plio",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="plio.plio"
            ),
        ),
        migrations.AlterField(
            model_name="session",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="sessionanswer",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="plio.question"
            ),
        ),
        migrations.AlterField(
            model_name="sessionanswer",
            name="session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="entries.session"
            ),
        ),
    ]
