# Generated by Django 3.1.1 on 2021-03-31 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("entries", "0005_auto_20210331_0645"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sessionanswer",
            name="answer",
            field=models.TextField(null=True),
        ),
    ]
