# Generated by Django 3.1.1 on 2021-04-01 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("entries", "0006_auto_20210331_0646"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="deleted_at",
        ),
        migrations.RemoveField(
            model_name="session",
            name="deleted_at",
        ),
        migrations.RemoveField(
            model_name="sessionanswer",
            name="deleted_at",
        ),
        migrations.AddField(
            model_name="event",
            name="deleted",
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name="session",
            name="deleted",
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name="sessionanswer",
            name="deleted",
            field=models.DateTimeField(editable=False, null=True),
        ),
    ]
