# Generated by Django 3.1.1 on 2021-04-05 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("experiments", "0005_auto_20210401_1340"),
        ("entries", "0007_auto_20210401_1340"),
    ]

    operations = [
        migrations.AlterField(
            model_name="session",
            name="experiment",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="experiments.experiment",
            ),
        ),
    ]
