# Generated by Django 3.1.1 on 2021-04-05 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("entries", "0009_auto_20210405_0940"),
    ]

    operations = [
        migrations.AlterField(
            model_name="session",
            name="retention",
            field=models.TextField(default=""),
        ),
    ]
