# Generated by Django 3.1.1 on 2021-04-08 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("entries", "0014_auto_20210408_0508"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="type",
            field=models.CharField(
                choices=[
                    ("played", "Played"),
                    ("paused", "Paused"),
                    ("enter_fullscreen", "Enter Fullscreen"),
                    ("exit_fullscreen", "Exit Fullscreen"),
                    ("option_selected", "Option Selected"),
                    ("question_opened", "Question Opened"),
                    ("question_skipped", "Question Skipped"),
                    ("question_answered", "Question Answered"),
                    ("question_revised", "Question Revised"),
                    ("question_proceed", "Question Proceeded"),
                    ("video_seeked", "Video Seeked"),
                ],
                max_length=255,
            ),
        ),
    ]
