# Generated by Django 3.1.1 on 2021-04-08 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("plio", "0017_merge_20210408_1358"),
        ("entries", "0016_auto_20210408_1503"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sessionanswer",
            name="question",
        ),
        migrations.AddField(
            model_name="sessionanswer",
            name="item",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="plio.item",
            ),
            preserve_default=False,
        ),
    ]
