# Generated by Django 3.1.1 on 2021-04-08 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("entries", "0017_auto_20210408_1942"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="sessionanswer",
            options={"ordering": ["item__time"]},
        ),
    ]
