# Generated by Django 3.1.1 on 2021-04-09 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("entries", "0019_auto_20210409_0607"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="type",
            field=models.CharField(
                choices=[
                    ("ready", "Player Ready"),
                    ("played", "Played"),
                    ("paused", "Paused"),
                    ("enter_fullscreen", "Enter Fullscreen"),
                    ("exit_fullscreen", "Exit Fullscreen"),
                    ("option_selected", "Option Selected"),
                    ("item_opened", "Item Opened"),
                    ("question_skipped", "Question Skipped"),
                    ("question_answered", "Question Answered"),
                    ("question_revised", "Question Revised"),
                    ("question_proceed", "Question Proceeded"),
                    ("video_seeked", "Video Seeked"),
                    ("watching", "Watching"),
                ],
                max_length=255,
            ),
        ),
    ]
