# Generated by Django 3.1.1 on 2021-04-10 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("entries", "0021_auto_20210409_0640"),
    ]

    operations = [
        migrations.AlterField(
            model_name="session",
            name="watch_time",
            field=models.FloatField(default=0),
        ),
    ]
