# Generated by Django 3.1.1 on 2021-08-30 05:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("plio", "0024_auto_20210830_0507"),
        ("entries", "0024_auto_20210830_0452"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="entries.session"
            ),
        ),
        migrations.AlterField(
            model_name="session",
            name="plio",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="plio.plio"
            ),
        ),
        migrations.AlterField(
            model_name="sessionanswer",
            name="item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="plio.item"
            ),
        ),
        migrations.AlterField(
            model_name="sessionanswer",
            name="session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="entries.session"
            ),
        ),
    ]
