# Generated by Django 3.1.1 on 2021-11-24 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0026_auto_20210830_0620'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-updated_at']},
        ),
    ]
