# Generated by Django 3.1.1 on 2025-04-07 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0028_auto_20211130_0828'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='has_video_played',
        ),
    ]
