event_type_choices = [
    ("ready", "Player Ready"),
    ("played", "Played"),
    ("paused", "Paused"),
    ("enter_fullscreen", "Enter Fullscreen"),
    ("exit_fullscreen", "Exit Fullscreen"),
    ("option_selected", "Option Selected"),
    ("question_opened", "Question Opened"),
    ("question_skipped", "Question Skipped"),
    ("question_answered", "Question Answered"),
    ("question_revised", "Question Revised"),
    ("question_proceed", "Question Proceeded"),
    ("video_seeked", "Video Seeked"),
    ("watching", "Watching"),
]
