name: Deployment

on:
  push:
    branches: [feature/deployment]
  release:
    types: ["created"]

jobs:
  deployment:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Set $VERSION variable
        id: version
        run: echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3)

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Publish to Container Registry
        env:
          VERSION: ${{ steps.version.outputs.VERSION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: make publish

      - uses: chrnorm/deployment-action@releases/v1
        name: Trigger Deployment
        id: deployment
        with:
          token: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
          environment: production
          ref: refs/tags/${{ steps.version.outputs.VERSION }}
