# Source https://github.com/marketplace/actions/aws-elastic-beanstalk-django-deployment
# Source for some errors:
# Config not set: https://gist.github.com/RobertoSchneiders/9e0e73e836a80d53a21e#gistcomment-1896478

name: Build and Deploy Django to EB

on:
  push:
    branches:
      - release

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python_version: [3.8.5]

    steps:
    - uses: actions/checkout@v2
    - name: Django aws eb deployment
      uses: joel-hanson/django-aws-eb-deploy@V1.1
      with:
        python_version: ${{ matrix.python_version }}
        flake8: false
        aws_access_key_id: ${{ secrets.aws_access_key_id }}
        aws_secret_access_key: ${{ secrets.aws_secret_access_key }}
        deploy: true
